spring.application.name=backend_equinorte
spring.datasource.url=jdbc:mysql://localhost:3306/equinorte
spring.datasource.username=root
spring.datasource.password=nieto1997
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true